apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: React-Client
  description: This is a dummy React app
  tags:
    - react
    - web
spec:
  type: website
  lifecycle: experimental
  owner: user:guest
  consumesApis:
    - api:product-api
    - api:weather-api
    - api:dummy-product-api
    - api:Tier1-token-api
    - api:Tier2-token-api
  dependsOn:
    - component:Product-App
    - component:weather-app
    - component:dummy-product-app  
    - component:Token-Balance-App
